"""add_schools

Revision ID: df62d182f881
Revises: b8c97e58b7a3
Create Date: 2026-05-18 12:10:35.039489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df62d182f881'
down_revision: Union[str, None] = 'b8c97e58b7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('district_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['school_districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_district_id'), 'schools', ['district_id'], unique=False)
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=False)
    op.add_column('users', sa.Column('school_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_foreign_key('fk_users_school_id', 'users', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_school_id', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_column('users', 'school_id')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.drop_index(op.f('ix_schools_district_id'), table_name='schools')
    op.drop_table('schools')
    # ### end Alembic commands ###
